"""
PDF report generator using ReportLab.
Generates monthly placement activity reports.
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.units import inch, cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import os


def generate_monthly_pdf(report_data: dict, output_path: str) -> str:
    """
    Generate a PDF monthly report.
    report_data: { month, drives_conducted, students_applied, students_selected, drives: [...] }
    Returns the output path.
    """
    doc = SimpleDocTemplate(output_path, pagesize=A4,
                            topMargin=1.5*cm, bottomMargin=1.5*cm,
                            leftMargin=2*cm, rightMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle('title', parent=styles['Title'],
                                  fontSize=20, textColor=colors.HexColor('#1e3a5f'),
                                  spaceAfter=6)
    story.append(Paragraph("Placement Portal", title_style))
    story.append(Paragraph(f"Monthly Activity Report — {report_data.get('month', 'N/A')}", styles['Heading2']))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#2563eb')))
    story.append(Spacer(1, 0.3*inch))

    # Summary stats table
    stat_data = [
        ['Metric', 'Count'],
        ['Placement Drives Conducted', str(report_data.get('drives_conducted', 0))],
        ['Students Applied', str(report_data.get('students_applied', 0))],
        ['Students Selected', str(report_data.get('students_selected', 0))],
    ]
    stat_table = Table(stat_data, colWidths=[4*inch, 2*inch])
    stat_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#2563eb')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 11),
        ('ALIGN', (1,0), (1,-1), 'CENTER'),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#f1f5f9'), colors.white]),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('PADDING', (0,0), (-1,-1), 8),
        ('ROWBACKGROUNDS', (0,2), (0,2), [colors.HexColor('#dcfce7')]),
    ]))
    story.append(stat_table)
    story.append(Spacer(1, 0.3*inch))

    # Drive details
    drives = report_data.get('drives', [])
    if drives:
        story.append(Paragraph("Drive Details", styles['Heading3']))
        drive_data = [['Drive Name', 'Company', 'Job Title', 'Applicants', 'Status']]
        for d in drives:
            drive_data.append([
                d.get('drive_name', ''), d.get('company_name', ''),
                d.get('job_title', ''), str(d.get('applicant_count', 0)), d.get('status', '')
            ])
        drive_table = Table(drive_data, colWidths=[1.8*inch, 1.5*inch, 1.5*inch, 0.8*inch, 0.8*inch])
        drive_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1e3a5f')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 9),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#f8fafc'), colors.white]),
            ('GRID', (0,0), (-1,-1), 0.3, colors.HexColor('#e2e8f0')),
            ('PADDING', (0,0), (-1,-1), 5),
            ('WORDWRAP', (0,0), (-1,-1), True),
        ]))
        story.append(drive_table)

    story.append(Spacer(1, 0.4*inch))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#cbd5e1')))
    story.append(Spacer(1, 0.1*inch))
    footer_style = ParagraphStyle('footer', parent=styles['Normal'], fontSize=8,
                                   textColor=colors.grey, alignment=TA_CENTER)
    story.append(Paragraph(
        f"Generated by Placement Portal on {datetime.utcnow().strftime('%d %B %Y, %H:%M UTC')}",
        footer_style
    ))

    doc.build(story)
    return output_path


def generate_student_report_pdf(student, applications, output_path: str) -> str:
    """Generate PDF placement history report for a student."""
    doc = SimpleDocTemplate(output_path, pagesize=A4,
                            topMargin=1.5*cm, bottomMargin=1.5*cm,
                            leftMargin=2*cm, rightMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Student Placement History Report", styles['Title']))
    story.append(Paragraph(f"Name: {student.full_name}  |  Roll: {student.roll_number or 'N/A'}  |  Dept: {student.department or 'N/A'}", styles['Normal']))
    story.append(Spacer(1, 0.2*inch))

    if not applications:
        story.append(Paragraph("No placement applications found.", styles['Normal']))
    else:
        data = [['#', 'Company', 'Drive', 'Job Title', 'Status', 'Date']]
        for i, a in enumerate(applications, 1):
            data.append([
                str(i),
                a.get('company_name', ''),
                a.get('drive_name', ''),
                a.get('job_title', ''),
                a.get('status', ''),
                a.get('application_date', '')[:10] if a.get('application_date') else '',
            ])
        t = Table(data, colWidths=[0.4*inch, 1.4*inch, 1.4*inch, 1.4*inch, 1*inch, 0.9*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#2563eb')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 9),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#f8fafc'), colors.white]),
            ('GRID', (0,0), (-1,-1), 0.3, colors.HexColor('#e2e8f0')),
            ('PADDING', (0,0), (-1,-1), 5),
        ]))
        story.append(t)

    doc.build(story)
    return output_path
